FROM remote-host

COPY ./conf/nginx.repo /etc/yum.repos.d/nginx.repo
RUN yum --enablerepo=extras install -y epel-release
RUN yum install -y php
RUN                                                                          \
  yum -y install nginx-1.12.2 openssl --enablerepo=nginx                  && \
  yum -y install https://centos7.iuscommunity.org/ius-release.rpm         && \
  yum -y install                                                             \
    php-fpm                                                               \
    php-cli                                                               \
    php-mysqlnd                                                           \
    php-soap                                                              \
    php-xml                                                               \
    php-zip                                                               \
    php-json                                                              \
    php-mcrypt                                                            \
    php-mbstring                                                          \
    php-zip                                                               \
    php-gd                                                                \
     --enablerepo=ius-archive && yum clean all

EXPOSE 80 443

VOLUME /var/www/html /var/log/nginx /var/log/php-fpm /var/lib/php-fpm

COPY ./conf/nginx.conf /etc/nginx/conf.d/default.conf

COPY ./bin/start.sh /start.sh

RUN chmod +x /start.sh

CMD /start.sh
